name: Test
on:
  push:
    branches-ignore: main
  pull_request:
    branches-ignore: main
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Deno environment
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.1.4

      - name: Run Deno Tests
        run: deno test --allow-all
